# These services have been deprecated and moved to automation blueprints
# This provides more flexibility and allows users to customize session logic
#
# Please use the automation blueprints instead:
# - Volcano Session Manager Blueprint
# - Volcano Temperature Sequence Blueprint
# - Volcano Fan Timer Blueprint
#
# See documentation for migration instructions and blueprint setup
