name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes
          - See [CHANGELOG.md](CHANGELOG.md) for details
          
          ## Installation
          1. Download the latest release
          2. Extract to your Home Assistant `custom_components` directory
          3. Restart Home Assistant
          4. Add the integration through the UI
          
          ## HACS Installation
          This integration is compatible with HACS for easier installation and updates.
        draft: false
        prerelease: false
